#spring:
#  datasource:
#    username: root
#    password: password
#    url: jdbc:mysql://localhost:3306/upschool
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
